import Link from "next/link";
import { ArrowLeft, BadgeCheck, HandCoins, ShieldCheck, Store, Truck } from "lucide-react";
import MarketplaceShell from "@/components/MarketplaceShell";

export default function SellPage(){
 return <MarketplaceShell title="Become a Vendor" subtitle="Join a trusted emergency-care marketplace built for verified partners.">
  <div className="grid gap-5 xl:grid-cols-[1fr_360px]">
   <section className="echo-card p-6 sm:p-8"><Link href="/marketplace" className="inline-flex items-center gap-2 text-xs font-bold text-echo-muted"><ArrowLeft size={14}/> Back to marketplace</Link><div className="mt-6 max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full bg-red-50 px-3 py-1.5 text-xs font-bold text-echo-red"><Store size={14}/> Marketplace partner</span><h2 className="mt-4 text-3xl font-extrabold">Sell products that help people prepare, respond and recover.</h2><p className="mt-3 text-sm leading-6 text-echo-muted">Emergency Echo connects verified vendors with people, healthcare teams and organizations looking for reliable emergency-care products and services.</p></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{[["Verified vendor profile",BadgeCheck],["Secure payments",ShieldCheck],["Reliable delivery",Truck],["Partner support",HandCoins]].map(([x,Icon])=><div key={x as string} className="echo-card-soft p-4"><Icon size={19} className="text-echo-red"/><div className="mt-2 text-sm font-extrabold">{x as string}</div></div>)}</div><div className="mt-7 grid gap-4 sm:grid-cols-2"><input className="rounded-xl border border-echo-border px-3 py-3 text-sm outline-none" placeholder="Business name"/><input className="rounded-xl border border-echo-border px-3 py-3 text-sm outline-none" placeholder="Business email"/><input className="rounded-xl border border-echo-border px-3 py-3 text-sm outline-none" placeholder="Phone number"/><input className="rounded-xl border border-echo-border px-3 py-3 text-sm outline-none" placeholder="Business location"/></div><button className="echo-btn-primary mt-4">Apply to become a vendor</button></section>
   <aside className="rounded-2xl bg-[#101010] p-6 text-white"><div className="text-lg font-extrabold">Marketplace standards</div><p className="mt-2 text-sm leading-6 text-white/70">Every marketplace partner is expected to provide accurate product information, transparent pricing and reliable fulfillment.</p><ul className="mt-6 space-y-4 text-sm">{["Verified business identity","Clear product specifications","Transparent pricing","Reliable customer support"].map(x=><li key={x} className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-white/10"><BadgeCheck size={14}/></span>{x}</li>)}</ul></aside>
  </div>
 </MarketplaceShell>
}
