import PartnershipShell from "@/components/PartnershipShell";
import { CheckCircle2, Download, FileText, Handshake, RefreshCw } from "lucide-react";
export default function Agreement(){return <PartnershipShell title="Partnership Agreement" subtitle="Manage active agreements and shared commitments.">
 <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]"><section className="echo-card p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-echo-border pb-5"><div><div className="text-lg font-extrabold">Emergency Echo × HopeCare Hospitals</div><div className="mt-1 text-xs text-echo-muted">Agreement ID • EE-PPT-2024-001</div></div><span className="rounded-full bg-green-50 px-3 py-1 text-[10px] font-bold text-green-700">Active</span></div>
 <div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Start date","Jan 15, 2024"],["End date","Jun 14, 2026"],["Status","Active"]].map(([a,b])=><div key={a} className="rounded-xl bg-gray-50 p-4"><div className="text-[9px] text-echo-muted">{a}</div><div className="mt-1 text-xs font-extrabold">{b}</div></div>)}</div>
 <div className="mt-6"><h2 className="font-extrabold">Scope of Partnership</h2><ul className="mt-3 space-y-2 text-xs text-echo-muted">{["Emergency response network","Health education","Community outreach"].map(x=><li key={x} className="flex items-center gap-2"><CheckCircle2 size={15} className="text-echo-green"/>{x}</li>)}</ul></div>
 <div className="mt-6"><h2 className="font-extrabold">Signed documents</h2><div className="mt-3 flex items-center gap-3 rounded-xl border border-echo-border p-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-red-50 text-echo-red"><FileText size={17}/></span><div className="flex-1"><div className="text-xs font-bold">Partnership_Agreement.pdf</div><div className="text-[10px] text-echo-muted">Signed on Jan 15, 2024</div></div><button className="echo-icon-btn h-9 w-9"><Download size={15}/></button></div></div>
 <div className="mt-6 flex flex-wrap gap-3"><button className="rounded-xl border border-echo-border px-4 py-3 text-xs font-bold">View Agreement</button><button className="echo-btn-primary"><RefreshCw size={15}/> Renew Partnership</button></div>
 </section><aside className="space-y-4"><div className="echo-card p-5"><div className="grid h-12 w-12 place-items-center rounded-xl bg-red-50 text-echo-red"><Handshake size={21}/></div><h2 className="mt-4 font-extrabold">Agreement health</h2><p className="mt-1 text-xs text-echo-muted">Your partnership is active and in good standing.</p><div className="mt-5 h-2 rounded-full bg-gray-100"><div className="h-2 w-[96%] rounded-full bg-echo-green"/></div><div className="mt-2 text-[10px] font-bold text-green-700">96% commitments on track</div></div><div className="rounded-2xl border border-red-100 bg-red-50 p-5"><div className="text-sm font-extrabold text-echo-red">Need a new agreement?</div><p className="mt-1 text-[10px] leading-4 text-echo-muted">Start a proposal for a new program or partner.</p></div></aside></div>
</PartnershipShell>}
