import PartnershipShell from "@/components/PartnershipShell";
import { ArrowRight, CheckCircle2, FileText, Target, UsersRound } from "lucide-react";
export default function Proposal(){return <PartnershipShell title="Propose a New Partnership" subtitle="Let's build something impactful together.">
 <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
  <section className="echo-card p-5 sm:p-6"><div className="mb-6 flex items-center gap-2">{["1. Details","2. Goals","3. Resources","4. Review"].map((x,i)=><div key={x} className="flex flex-1 items-center gap-2 text-[10px] font-bold"><span className={`grid h-7 w-7 place-items-center rounded-full ${i===0?"bg-echo-red text-white":"bg-gray-100 text-echo-muted"}`}>{i+1}</span><span className="hidden sm:block">{x.slice(3)}</span>{i<3&&<span className="h-px flex-1 bg-echo-border"/>}</div>)}</div>
   <div className="grid gap-4 md:grid-cols-2"><Field label="Program title" value="Community First Responder Training"/><Field label="Program category" value="Training & Capacity Building"/><Field label="Target community" value="Rural Communities"/><Field label="Expected impact" value="5,000 people"/></div>
   <label className="mt-4 block"><span className="text-xs font-bold">Program description</span><textarea className="mt-2 min-h-28 w-full rounded-xl border border-echo-border p-3 text-sm outline-none focus:border-red-300" defaultValue="Training community members on basic first aid and emergency response to improve first response time."/></label>
   <div className="mt-6 flex flex-wrap justify-end gap-3"><button className="rounded-xl border border-echo-border px-4 py-3 text-xs font-bold">Save Draft</button><button className="echo-btn-primary">Next: Set Goals <ArrowRight size={16}/></button></div>
  </section>
  <aside className="space-y-4"><div className="echo-card p-5"><h2 className="font-extrabold">What makes a strong proposal?</h2><div className="mt-4 space-y-4">{[["Clear goal","Define the outcome your program will create.",Target],["Community need","Explain who benefits and why.",UsersRound],["Shared resources","Outline what each partner contributes.",FileText]].map(([a,b,I])=><div key={a as string} className="flex gap-3"><I size={17} className="mt-0.5 text-echo-red"/><div><div className="text-xs font-bold">{a as string}</div><p className="mt-1 text-[10px] leading-4 text-echo-muted">{b as string}</p></div></div>)}</div></div><div className="rounded-2xl border border-green-200 bg-green-50 p-5"><div className="flex items-center gap-2 text-xs font-bold text-green-800"><CheckCircle2 size={16}/> Secure proposal workspace</div><p className="mt-2 text-[10px] leading-4 text-green-700">Your draft remains private until you submit it for partner review.</p></div></aside>
 </div>
</PartnershipShell>}
function Field({label,value}:{label:string;value:string}){return <label className="block"><span className="text-xs font-bold">{label}</span><input className="mt-2 w-full rounded-xl border border-echo-border px-3 py-3 text-sm outline-none focus:border-red-300" defaultValue={value}/></label>}
