import PartnershipShell from "@/components/PartnershipShell";
import Avatar from "@/components/Avatar";
import { MapPin, Search, ShieldCheck, SlidersHorizontal } from "lucide-react";
const partners=[["HopeCare Hospitals","Healthcare Provider","Lagos, Nigeria","Verified"],["Red Cross Nigeria","NGO","Abuja, Nigeria","Verified"],["LifeLine Ambulance","Emergency Services","Lagos, Nigeria","Verified"],["MedServe Solutions","Healthcare Supplier","Lagos, Nigeria","Verified"],["HealthBridge Africa","Community Health","Ibadan, Nigeria","Verified"],["CareConnect Network","Health Technology","Accra, Ghana","Verified"]];
export default function Directory(){return <PartnershipShell title="Partner Directory" subtitle="Our trusted partners working together for a safer world.">
 <section className="echo-card p-5"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search size={16} className="absolute left-3 top-3.5 text-echo-muted"/><input placeholder="Search partner..." className="w-full rounded-xl border border-echo-border py-3 pl-9 pr-3 text-sm outline-none focus:border-red-300"/></label><button className="echo-icon-btn"><SlidersHorizontal size={17}/></button><select className="rounded-xl border border-echo-border px-3 text-xs font-semibold"><option>All Categories</option><option>Healthcare</option><option>NGO</option><option>Emergency Services</option></select><select className="rounded-xl border border-echo-border px-3 text-xs font-semibold"><option>All Locations</option><option>Lagos</option><option>Abuja</option></select></div>
  <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{partners.map(([name,cat,loc,status])=><article key={name} className="rounded-2xl border border-echo-border p-4"><div className="flex items-center gap-3"><Avatar name={name} className="h-12 w-12"/><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-extrabold">{name}</h2><p className="text-[10px] text-echo-muted">{cat}</p></div><ShieldCheck size={16} className="text-echo-green"/></div><div className="mt-4 flex items-center justify-between border-t border-echo-border pt-3"><span className="flex items-center gap-1 text-[10px] text-echo-muted"><MapPin size={12}/>{loc}</span><span className="rounded-full bg-green-50 px-2 py-1 text-[9px] font-bold text-green-700">{status}</span></div></article>)}</div>
  <div className="mt-5 flex justify-center"><button className="rounded-xl border border-echo-border px-4 py-3 text-xs font-bold text-echo-red">View all partners →</button></div>
 </section>
</PartnershipShell>}
