import PartnershipShell from "@/components/PartnershipShell";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, Plus, UsersRound } from "lucide-react";
import Link from "next/link";
const programs=[{name:"Emergency Response Network",cat:"Emergency response",status:"Active",impact:"12,458 lives impacted",date:"Since Jan 2024"},{name:"Health Education Initiative",cat:"Training & capacity building",status:"Active",impact:"8,742 lives impacted",date:"Since Mar 2024"},{name:"Maternal Care Support",cat:"Community outreach",status:"Upcoming",impact:"2,354 lives expected",date:"Starts Aug 2026"},{name:"Rural Health Outreach",cat:"Community outreach",status:"Completed",impact:"6,345 lives reached",date:"Completed May 2026"}];
export default function Programs(){return <PartnershipShell title="Partnership Programs" subtitle="Design, launch and track collaborative programs.">
 <div className="echo-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-1 rounded-xl bg-gray-50 p-1">{["All","Active","Upcoming","Completed"].map((x,i)=><button key={x} className={`rounded-lg px-3 py-2 text-xs font-bold ${i===0?"bg-white text-echo-red shadow-card":"text-echo-muted"}`}>{x}</button>)}</div><Link href="/partnership/proposal" className="echo-btn-primary"><Plus size={16}/> Propose New Program</Link></div>
  <div className="mt-5 grid gap-3 lg:grid-cols-2">{programs.map(p=><article key={p.name} className="rounded-2xl border border-echo-border p-4"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-echo-red"><BriefcaseBusiness size={18}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-extrabold">{p.name}</h2><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${p.status==="Active"?"bg-green-50 text-green-700":p.status==="Upcoming"?"bg-yellow-50 text-yellow-700":"bg-gray-100 text-gray-600"}`}>{p.status}</span></div><p className="mt-1 text-xs text-echo-muted">{p.cat}</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-gray-50 p-3"><div className="text-[9px] text-echo-muted">Impact</div><div className="mt-1 text-xs font-extrabold">{p.impact}</div></div><div className="rounded-xl bg-gray-50 p-3"><div className="text-[9px] text-echo-muted">Timeline</div><div className="mt-1 text-xs font-extrabold">{p.date}</div></div></div></div></div><button className="mt-4 flex items-center gap-1 text-xs font-bold text-echo-red">View program <ArrowRight size={14}/></button></article>)}</div>
 </div>
 <div className="mt-4 grid gap-4 md:grid-cols-3">{[["24","Active partnerships",UsersRound],["78","Communities served",CheckCircle2],["156","Resources shared",BriefcaseBusiness]].map(([v,l,I])=><div key={l as string} className="echo-card p-5"><I size={18} className="text-echo-red"/><div className="mt-3 text-2xl font-extrabold">{v as string}</div><div className="text-xs text-echo-muted">{l as string}</div></div>)}</div>
</PartnershipShell>}
