import AppShell from "@/components/AppShell";
import Link from "next/link";
import StatusBadge from "@/components/StatusBadge";
import Waveform from "@/components/Waveform";
import { Mic, Phone, Ambulance, Bell, MapPin, Activity, HeartPulse, Thermometer, ShieldAlert, Video, MessageCircle } from "lucide-react";
export default function AI(){return <AppShell title="AI Assistant" subtitle="Voice-first emergency guidance" mode="live">
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(360px,.9fr)]">
  <section className="overflow-hidden rounded-2xl bg-[#0b1830] p-5 text-white shadow-lift sm:p-7">
   <div className="flex items-center justify-between"><StatusBadge tone="neutral">AI Assistant</StatusBadge><StatusBadge tone="success" dot>Listening</StatusBadge></div>
   <div className="flex min-h-[560px] flex-col items-center justify-center text-center"><div className="relative grid h-44 w-44 place-items-center rounded-full border-8 border-blue-400/20"><div className="grid h-32 w-32 place-items-center rounded-full bg-echo-blue text-white shadow-[0_0_60px_rgba(0,122,255,.35)]"><Mic size={48}/></div></div><h2 className="mt-8 text-2xl font-extrabold">I&apos;m listening...</h2><div className="mt-5 w-full max-w-md"><Waveform bars={34} tone="blue"/></div><div className="mt-8 grid w-full max-w-md grid-cols-3 gap-2">{[["72","BPM",HeartPulse],["97%","SpO₂",Activity],["36.5°","Temp",Thermometer]].map(([v,l,I])=>{const Icon=I as any;return <div key={l as string} className="rounded-xl border border-white/10 bg-white/10 p-3"><Icon size={16} className="mx-auto text-blue-300"/><div className="mt-2 text-lg font-bold">{v as string}</div><div className="text-[10px] text-gray-300">{l as string}</div></div>})}</div></div>
  </section>
  <div className="space-y-4">
   <div className="echo-card p-6"><div className="eyebrow">AI triage</div><div className="mt-2 flex items-start justify-between gap-3"><div><h2 className="text-2xl font-extrabold">Possible emergency detected</h2><p className="mt-2 text-sm leading-6 text-echo-muted">Demo state based on the UI spreadsheet. Confidence and diagnosis should be supplied by the real triage service.</p></div><StatusBadge tone="danger">93%</StatusBadge></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full w-[93%] rounded-full bg-echo-red"/></div><div className="mt-5 grid gap-2 sm:grid-cols-2"><Link href="/doctor" className="echo-btn-primary"><Phone size={16}/> Call doctor</Link><button className="echo-btn-secondary"><Ambulance size={16}/> Call ambulance</button><button className="echo-btn-secondary"><Bell size={16}/> Notify family</button><button className="echo-btn-secondary"><MapPin size={16}/> Share location</button><Link href="/video-call" className="echo-btn-secondary sm:col-span-2"><Video size={16}/> Open video call</Link></div></div>
   <div className="echo-card p-5"><div className="flex items-center justify-between"><div><div className="eyebrow">AI context</div><h2 className="mt-1 font-extrabold">What the assistant is monitoring</h2></div><MessageCircle size={18} className="text-echo-red"/></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-gray-50 p-3 text-xs font-semibold">Symptoms</div><div className="rounded-xl bg-gray-50 p-3 text-xs font-semibold">Breathing</div><div className="rounded-xl bg-gray-50 p-3 text-xs font-semibold">Vital trends</div></div></div>
   <div className="rounded-2xl border border-red-100 bg-red-50 p-5"><div className="flex items-center gap-2 text-sm font-bold text-echo-red"><ShieldAlert size={18}/> Emergency guidance</div><p className="mt-2 text-xs leading-5 text-echo-muted">If you believe there is an immediate danger, use the emergency action rather than waiting for AI analysis to finish.</p></div>
  </div>
 </div>
 </AppShell>}
