export const pages = [
  { id: 'login', label: 'Log In', isPrivate: false, roles: [] },
  { id: 'signup', label: 'Create Account', isPrivate: false, roles: [] },

  { id: 'kit', label: 'Digital Medical Kit', isPrivate: true, roles: ['patient', 'partner', 'admin'] },
  { id: 'echo-qr', label: 'Emergency QR', isPrivate: true, roles: ['patient', 'admin'] },
  // AI chat remains available via in-app entry points (home card / voice AI), but is not a primary nav destination.
  { id: 'chat', label: 'EchoAI', isPrivate: true, roles: ['patient', 'admin'], hideInNav: true },
  { id: 'home', label: 'Home', isPrivate: true, roles: [] },
  { id: 'voice-ai', label: 'Voice AI', isPrivate: true, roles: ['patient', 'admin'] },
  { id: 'marketplace', label: 'Marketplace', isPrivate: true, roles: [] },
  { id: 'marketplace-categories', label: 'Marketplace Categories', isPrivate: true, roles: [], hideInNav: true },
  { id: 'marketplace-products', label: 'Product Listing', isPrivate: true, roles: [], hideInNav: true },
  { id: 'marketplace-product', label: 'Product Details', isPrivate: true, roles: [], hideInNav: true },
  { id: 'marketplace-vendor', label: 'Vendor Store', isPrivate: true, roles: [], hideInNav: true },
  { id: 'marketplace-checkout', label: 'Checkout', isPrivate: true, roles: [], hideInNav: true },
  { id: 'marketplace-sell', label: 'Become a Vendor', isPrivate: true, roles: [], hideInNav: true },
  { id: 'partnership', label: 'Partnerships', isPrivate: true, roles: [] },
  { id: 'partnership-programs', label: 'Partnership Programs', isPrivate: true, roles: [], hideInNav: true },
  { id: 'partnership-proposal', label: 'New Partnership', isPrivate: true, roles: [], hideInNav: true },
  { id: 'partnership-directory', label: 'Partner Directory', isPrivate: true, roles: [], hideInNav: true },
  { id: 'partnership-analytics', label: 'Partnership Analytics', isPrivate: true, roles: [], hideInNav: true },
  { id: 'partnership-agreement', label: 'Partnership Agreement', isPrivate: true, roles: [], hideInNav: true },
  { id: 'wallet', label: 'EchoWallet', isPrivate: true, roles: [] },
  { id: 'wallet-add-funds', label: 'Add Funds', isPrivate: true, roles: [], hideInNav: true },
  { id: 'wallet-withdraw', label: 'Withdraw Funds', isPrivate: true, roles: ['doctor', 'nurse', 'admin'], hideInNav: true },
  { id: 'notifications', label: 'Notifications', isPrivate: true, roles: [] },
  { id: 'profile', label: 'Profile', isPrivate: true, roles: [] },
  { id: 'profile-basic', label: 'Basic Information', isPrivate: true, roles: [], hideInNav: true },
  { id: 'profile-emergency', label: 'Emergency Contact', isPrivate: true, roles: [], hideInNav: true },
  { id: 'profile-password', label: 'Password', isPrivate: true, roles: [], hideInNav: true },
  { id: 'profile-notifications', label: 'Notification Settings', isPrivate: true, roles: [], hideInNav: true },
  { id: 'directory', label: 'Users', isPrivate: true, roles: ['admin'] },
  { id: 'admin', label: 'Admin', isPrivate: true, roles: ['admin'] },
  { id: 'admin-login', label: 'Admin Login', isPrivate: false, roles: [], hideInNav: true },
  { id: 'admin-users', label: 'Admin: Users', isPrivate: true, roles: ['admin'], hideInNav: true },
  { id: 'admin-wallet', label: 'Admin: Wallet', isPrivate: true, roles: ['admin'], hideInNav: true },
  { id: 'admin-plans', label: 'Admin: Plans', isPrivate: true, roles: ['admin'], hideInNav: true },
  { id: 'admin-roles', label: 'Admin: Roles', isPrivate: true, roles: ['admin'], hideInNav: true },
  { id: 'admin-pages', label: 'Admin: Pages', isPrivate: true, roles: ['admin'], hideInNav: true },
  { id: 'admin-queue', label: 'Admin: Queue', isPrivate: true, roles: ['admin'], hideInNav: true },
  { id: 'admin-verification', label: 'Admin: Verification', isPrivate: true, roles: ['admin'], hideInNav: true },
  { id: 'doctor-profile', label: 'Doctor Profile', isPrivate: true, roles: [], hideInNav: true },

  // Role-gated / professional tools.
  { id: 'video-call', label: 'Video Call', isPrivate: true, roles: [] },
  { id: 'doctor-live', label: 'Live Session', isPrivate: true, roles: [], hideInNav: true },
  { id: 'patient-live', label: 'Live Session', isPrivate: true, roles: [], hideInNav: true },
  { id: 'doctor-wait', label: 'Waiting Room', isPrivate: true, roles: [], hideInNav: true },
  { id: 'payment', label: 'Buy Call Credit', isPrivate: true, roles: [], hideInNav: true },
  { id: 'consultation-payment', label: 'Consultation Authorization', isPrivate: true, roles: [], hideInNav: true },
  { id: 'consultation-mode', label: 'Consultation Mode', isPrivate: true, roles: [], hideInNav: true },
  { id: 'consultation-waiting', label: 'Connecting...', isPrivate: true, roles: [], hideInNav: true },

  // Applications / onboarding flows.
  { id: 'apply-user', label: 'Patient Setup', isPrivate: true, roles: ['patient'], hideInNav: true },
  { id: 'apply-doctor', label: 'Doctor Application', isPrivate: true, roles: ['doctor'], hideInNav: true },
  { id: 'apply-nurse', label: 'Nurse Application', isPrivate: true, roles: ['nurse'], hideInNav: true },
  { id: 'apply-partner', label: 'Partner Application', isPrivate: true, roles: ['partner'], hideInNav: true },
  { id: 'subscription', label: 'Upgrade Plan', isPrivate: true, roles: [] },
  { id: 'language', label: 'Language / Ede', isPrivate: true, roles: [] },
  { id: 'forbidden', label: 'Access Denied', isPrivate: false, roles: [] },
]
